version: "3.9"

services:
  orders-db:
    image: postgres:16
    container_name: orders-db
    restart: always
    environment:
      POSTGRES_USER: serdev
      POSTGRES_PASSWORD: nifer2030
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - orders-network

  orders-service:
    build: .
    container_name: orders-service
    restart: always
    depends_on:
      - orders-db
    environment:
      DB_HOST: orders-db
      DB_PORT: 5432
      DB_USERNAME: serdev
      DB_PASSWORD: nifer2030
      DB_DATABASE: orders_db
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: grupo8
    ports:
      - "3000:3000"
    networks:
      - orders-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-orders
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - orders-db
    networks:
      - orders-network

volumes:
  orders_data:

networks:
  orders-network:
    driver: bridge
